"""AIRank evidence primitives."""

from .fact_source import fact_source_ref_from_citation
from .citation_support import (
    CitationClaim,
    CitationSupportEvidenceGrade,
    CitationSupportLabel,
    CitationSupportMetrics,
    CitationSupportReview,
    calculate_citation_support_metrics,
)
from .evidence_snapshot import EvidenceSnapshot
from .fact_accuracy import (
    AnswerClaimKind,
    FactAccuracyClaim,
    FactAccuracyEvidenceGrade,
    FactAccuracyMetrics,
    FactAccuracyReview,
    FactAccuracyVerdict,
    calculate_fact_accuracy_metrics,
)
from .gap import generate_gap_from_citations
from .object_storage import (
    FilesystemObjectStorage,
    ObjectStorage,
    ObjectStorageError,
    READINESS_OBJECT_KEY,
    READINESS_OBJECT_PAYLOAD,
    S3CompatibleObjectStorage,
    StoredObject,
    build_object_storage_from_env,
    provision_object_storage_readiness,
    sha256_bytes,
    verify_object_storage_readiness,
)
from .provider import MockAnswerProvider, ProviderPayloadError
from .report import (
    EvidenceReport,
    METRIC_FORMULAS,
    REPORT_EVIDENCE_PACKET_VERSION,
    SOURCE_GOVERNANCE_VERSION,
    ReportArtifactRenderError,
    ReportConclusion,
    ReportEvidencePacket,
    ReportEvidencePacketError,
    build_report_conclusion,
    build_report_evidence_packet,
    canonical_json_bytes,
    canonical_json_sha256,
)
from .report_verifier import (
    ReportEvidencePacketVerification,
    ReportEvidencePacketVerificationError,
    verify_report_evidence_packet,
)
from .review_bundle import (
    REPORT_REVIEW_BUNDLE_MEMBERS,
    REPORT_REVIEW_BUNDLE_VERSION,
    render_report_docx,
    render_report_html,
    render_report_pdf,
    render_report_readme,
    render_scorecard_csv,
)
from .snapshot import AnswerSnapshot, SourceCitation
from .source_registry import (
    SourceClassificationRevision,
    current_source_classification,
    normalize_source_host,
)
from .review_quality import (
    FINAL_REVIEW_STATUSES,
    IndependentReviewPair,
    ReviewQualityMetrics,
    calculate_review_quality_metrics,
)

__all__ = [
    "AnswerSnapshot",
    "AnswerClaimKind",
    "CitationClaim",
    "CitationSupportEvidenceGrade",
    "CitationSupportLabel",
    "CitationSupportMetrics",
    "CitationSupportReview",
    "MockAnswerProvider",
    "ProviderPayloadError",
    "EvidenceReport",
    "EvidenceSnapshot",
    "FactAccuracyClaim",
    "FactAccuracyEvidenceGrade",
    "FactAccuracyMetrics",
    "FactAccuracyReview",
    "FactAccuracyVerdict",
    "FINAL_REVIEW_STATUSES",
    "FilesystemObjectStorage",
    "ObjectStorageError",
    "ObjectStorage",
    "READINESS_OBJECT_KEY",
    "READINESS_OBJECT_PAYLOAD",
    "METRIC_FORMULAS",
    "REPORT_EVIDENCE_PACKET_VERSION",
    "SOURCE_GOVERNANCE_VERSION",
    "ReportArtifactRenderError",
    "ReportConclusion",
    "ReportEvidencePacket",
    "ReportEvidencePacketError",
    "ReportEvidencePacketVerification",
    "ReportEvidencePacketVerificationError",
    "REPORT_REVIEW_BUNDLE_MEMBERS",
    "REPORT_REVIEW_BUNDLE_VERSION",
    "SourceCitation",
    "SourceClassificationRevision",
    "IndependentReviewPair",
    "ReviewQualityMetrics",
    "S3CompatibleObjectStorage",
    "StoredObject",
    "build_object_storage_from_env",
    "calculate_citation_support_metrics",
    "calculate_fact_accuracy_metrics",
    "calculate_review_quality_metrics",
    "sha256_bytes",
    "build_report_conclusion",
    "build_report_evidence_packet",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "fact_source_ref_from_citation",
    "generate_gap_from_citations",
    "current_source_classification",
    "normalize_source_host",
    "provision_object_storage_readiness",
    "render_report_html",
    "render_report_pdf",
    "render_report_readme",
    "render_report_docx",
    "render_scorecard_csv",
    "verify_report_evidence_packet",
    "verify_object_storage_readiness",
]
